	db "IRON BALL@" ; species name
	dw 200, 2099 ; height, weight

	db   "The magnetic force"
	next "generated by its"
	next "body repels the"

	page "ground's natural"
	next "magnetism, letting"
	next "it float.@"
