	tilepal 0, GRAY, GRAY, BROWN, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GRAY, BROWN, BROWN, GRAY, GRAY, BROWN, BROWN, ROOF
	tilepal 0, GRAY, GRAY, BROWN, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GRAY, BROWN, BROWN, GRAY, GRAY, BROWN, BROWN, RED
