	tilepal 0, GRAY, WATER, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 0, BROWN, BROWN, GRAY, GRAY, RED, RED, BROWN, BROWN
	tilepal 0, ROOF, ROOF, BROWN, BROWN, BROWN, BROWN, GRAY, GRAY
	tilepal 0, ROOF, ROOF, GRAY, GRAY, ROOF, ROOF, BROWN, BROWN
	tilepal 0, ROOF, ROOF, GREEN, WATER, WATER, WATER, GRAY, RED
	tilepal 0, BROWN, BROWN, BROWN, BROWN, GREEN, GREEN, BROWN, BROWN
	tilepal 0, ROOF, ROOF, GREEN, GREEN, RED, RED, GRAY, RED
	tilepal 0, RED, RED, BROWN, BROWN, GREEN, GREEN, BROWN, BROWN
	tilepal 0, BROWN, BROWN, BROWN, GREEN, GREEN, GRAY, BROWN, WATER
	tilepal 0, BROWN, BROWN, GRAY, BROWN, BROWN, BROWN, BROWN, WATER
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, GRAY, BROWN, ROOF
	tilepal 0, ROOF, ROOF, GRAY, BROWN, GRAY, GRAY, GRAY, GRAY

rept 16
	db $ff
endr

	tilepal 1, GREEN, GREEN, GREEN, GREEN, WATER, WATER, WATER, YELLOW
	tilepal 1, YELLOW, GREEN, GREEN, GRAY, GRAY, BROWN, BROWN, TEXT
	tilepal 1, GREEN, GREEN, GREEN, GREEN, ROOF, WATER, WATER, GRAY
	tilepal 1, GRAY, GREEN, GREEN, GRAY, GRAY, BROWN, BROWN, TEXT
	tilepal 1, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT
	tilepal 1, TEXT, TEXT, TEXT, GRAY, GRAY, TEXT
