	tilepal 0, GRAY, GRAY, GRAY, GREEN, GRAY, GREEN, BROWN, BROWN
	tilepal 0, GRAY, GRAY, GRAY, GRAY, BROWN, BROWN, GRAY, YELLOW
	tilepal 0, GRAY, GRAY, GRAY, BROWN, RED, BROWN, BROWN, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, BROWN
	tilepal 0, WATER, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, GRAY
	tilepal 0, GRAY, BROWN, BROWN, GREEN, GREEN, TEXT, GRAY, GRAY
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, GRAY
	tilepal 0, TEXT, BROWN, BROWN, GREEN, GREEN, TEXT, GRAY, GRAY
