	tilepal 0, GRAY, GREEN, BROWN, BROWN, GREEN, GREEN, GREEN, GREEN
	tilepal 0, GREEN, GREEN, GREEN, GREEN, BROWN, BROWN, YELLOW, YELLOW
	tilepal 0, GRAY, GREEN, BROWN, BROWN, GREEN, GREEN, GREEN, GREEN
	tilepal 0, GREEN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, BROWN, GRAY, YELLOW
	tilepal 0, BROWN, RED, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, TEXT
