	tilepal 0, GRAY, BROWN, BROWN, RED, BROWN, ROOF, ROOF, ROOF
	tilepal 0, ROOF, ROOF, YELLOW, YELLOW, YELLOW, GRAY, BROWN, GRAY
	tilepal 0, GRAY, BROWN, ROOF, BROWN, WATER, ROOF, ROOF, ROOF
	tilepal 0, ROOF, ROOF, GRAY, BROWN, BROWN, GRAY, BROWN, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, BROWN, ROOF, ROOF, BROWN
	tilepal 0, ROOF, ROOF, GRAY, GRAY, GREEN, GREEN, GREEN, GRAY
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 0, ROOF, GRAY, GRAY, GRAY, GRAY, GREEN, GREEN, GRAY
	tilepal 0, GREEN, GREEN, GRAY, GRAY, GRAY, GRAY, BROWN, BROWN
	tilepal 0, BROWN, BROWN, GRAY, BROWN, GRAY, GRAY, GRAY, RED
	tilepal 0, GREEN, GREEN, GREEN, ROOF, BROWN, BROWN, BROWN, BROWN
	tilepal 0, BROWN, BROWN, GRAY, BROWN, GRAY, GRAY, GRAY, GRAY

rept 16
	db $ff
endr

	tilepal 1, GRAY, GRAY, BROWN, BROWN, GRAY, GRAY, GRAY, GRAY
	tilepal 1, BROWN, BROWN, BROWN, ROOF, ROOF, BROWN, GRAY, GRAY
	tilepal 1, GRAY, GRAY, BROWN, BROWN, GRAY, GRAY, ROOF, ROOF
	tilepal 1, BROWN, BROWN, BROWN, ROOF, ROOF, BROWN, GRAY, GRAY
	tilepal 1, TEXT, TEXT, TEXT, TEXT, GRAY, GRAY, TEXT, TEXT
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, TEXT
	tilepal 1, GRAY, GRAY, GRAY, GRAY, TEXT, TEXT, TEXT, TEXT
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, TEXT
	tilepal 1, GRAY, GRAY, GRAY, GRAY, TEXT, TEXT, TEXT, TEXT
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 1, GRAY, GRAY, GRAY, GRAY, TEXT, TEXT, TEXT, TEXT
	tilepal 1, BROWN, BROWN, BROWN, TEXT, GRAY, GRAY, GRAY, GRAY
