	tilepal 0, GRAY, GRAY, BROWN, GRAY, GRAY, GREEN, GREEN, BROWN
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, BROWN, BROWN, BROWN
	tilepal 0, GRAY, WATER, RED, GRAY, GRAY, GREEN, GREEN, BROWN
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, BROWN, BROWN, BROWN
	tilepal 0, GREEN, GREEN, RED, RED, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GRAY, WATER, WATER, WATER, WATER, WATER, WATER
	tilepal 0, GREEN, GREEN, WATER, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GRAY, WATER, WATER, WATER, GRAY, GRAY, WATER
	tilepal 0, GRAY, GRAY, BROWN, BROWN, GRAY, BROWN, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, TEXT, TEXT, TEXT, TEXT
	tilepal 0, GRAY, GRAY, BROWN, BROWN, BROWN, BROWN, BROWN, TEXT
	tilepal 0, GRAY, GRAY, GRAY, GRAY
