	tilepal 0, GRAY, GRAY, GRAY, GREEN, GRAY, GREEN, BROWN, BROWN
	tilepal 0, GRAY, GRAY, GRAY, GRAY, BROWN, BROWN, GRAY, YELLOW
	tilepal 0, GRAY, GRAY, GRAY, BROWN, RED, BROWN, BROWN, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, BROWN
	tilepal 0, WATER, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, GRAY
	tilepal 0, GRAY, BROWN, RED, RED, RED, GRAY, GRAY, GRAY
	tilepal 0, BROWN, BROWN, BROWN, YELLOW, GREEN, GREEN, YELLOW, GRAY
	tilepal 0, YELLOW, YELLOW, RED, RED, RED, GRAY, GRAY, GRAY
	tilepal 0, YELLOW, YELLOW, BROWN, BROWN, GREEN, GREEN, BROWN, BROWN
	tilepal 0, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, BROWN, BROWN, BROWN
	tilepal 0, GRAY, GRAY, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN

rept 16
	db $ff
endr

	tilepal 1, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 1, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 1, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 1, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 1, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 1, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 1, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 1, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 1, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 1, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 1, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 1, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
