BitmasksPointers:
	dw BulbasaurBitmasks
	dw IvysaurBitmasks
	dw VenusaurBitmasks
	dw CharmanderBitmasks
	dw CharmeleonBitmasks
	dw CharizardBitmasks
	dw SquirtleBitmasks
	dw WartortleBitmasks
	dw BlastoiseBitmasks
	dw CaterpieBitmasks
	dw MetapodBitmasks
	dw ButterfreeBitmasks
	dw WeedleBitmasks
	dw KakunaBitmasks
	dw BeedrillBitmasks
	dw PidgeyBitmasks
	dw PidgeottoBitmasks
	dw PidgeotBitmasks
	dw RattataBitmasks
	dw RaticateBitmasks
	dw SpearowBitmasks
	dw FearowBitmasks
	dw EkansBitmasks
	dw ArbokBitmasks
	dw PikachuBitmasks
	dw RaichuBitmasks
	dw SandshrewBitmasks
	dw SandslashBitmasks
	dw NidoranFBitmasks
	dw NidorinaBitmasks
	dw NidoqueenBitmasks
	dw NidoranMBitmasks
	dw NidorinoBitmasks
	dw NidokingBitmasks
	dw ClefairyBitmasks
	dw ClefableBitmasks
	dw VulpixBitmasks
	dw NinetalesBitmasks
	dw JigglypuffBitmasks
	dw WigglytuffBitmasks
	dw ZubatBitmasks
	dw GolbatBitmasks
	dw OddishBitmasks
	dw GloomBitmasks
	dw VileplumeBitmasks
	dw ParasBitmasks
	dw ParasectBitmasks
	dw VenonatBitmasks
	dw VenomothBitmasks
	dw DiglettBitmasks
	dw DugtrioBitmasks
	dw MeowthBitmasks
	dw PersianBitmasks
	dw PsyduckBitmasks
	dw GolduckBitmasks
	dw MankeyBitmasks
	dw PrimeapeBitmasks
	dw GrowlitheBitmasks
	dw ArcanineBitmasks
	dw PoliwagBitmasks
	dw PoliwhirlBitmasks
	dw PoliwrathBitmasks
	dw AbraBitmasks
	dw KadabraBitmasks
	dw AlakazamBitmasks
	dw MachopBitmasks
	dw MachokeBitmasks
	dw MachampBitmasks
	dw BellsproutBitmasks
	dw WeepinbellBitmasks
	dw VictreebelBitmasks
	dw TentacoolBitmasks
	dw TentacruelBitmasks
	dw GeodudeBitmasks
	dw GravelerBitmasks
	dw GolemBitmasks
	dw PonytaBitmasks
	dw RapidashBitmasks
	dw SlowpokeBitmasks
	dw SlowbroBitmasks
	dw MagnemiteBitmasks
	dw MagnetonBitmasks
	dw FarfetchDBitmasks
	dw DoduoBitmasks
	dw DodrioBitmasks
	dw SeelBitmasks
	dw DewgongBitmasks
	dw GrimerBitmasks
	dw MukBitmasks
	dw ShellderBitmasks
	dw CloysterBitmasks
	dw GastlyBitmasks
	dw HaunterBitmasks
	dw GengarBitmasks
	dw OnixBitmasks
	dw DrowzeeBitmasks
	dw HypnoBitmasks
	dw KrabbyBitmasks
	dw KinglerBitmasks
	dw VoltorbBitmasks
	dw ElectrodeBitmasks
	dw ExeggcuteBitmasks
	dw ExeggutorBitmasks
	dw CuboneBitmasks
	dw MarowakBitmasks
	dw HitmonleeBitmasks
	dw HitmonchanBitmasks
	dw LickitungBitmasks
	dw KoffingBitmasks
	dw WeezingBitmasks
	dw RhyhornBitmasks
	dw RhydonBitmasks
	dw ChanseyBitmasks
	dw TangelaBitmasks
	dw KangaskhanBitmasks
	dw HorseaBitmasks
	dw SeadraBitmasks
	dw GoldeenBitmasks
	dw SeakingBitmasks
	dw StaryuBitmasks
	dw StarmieBitmasks
	dw MrMimeBitmasks
	dw ScytherBitmasks
	dw JynxBitmasks
	dw ElectabuzzBitmasks
	dw MagmarBitmasks
	dw PinsirBitmasks
	dw TaurosBitmasks
	dw MagikarpBitmasks
	dw GyaradosBitmasks
	dw LaprasBitmasks
	dw DittoBitmasks
	dw EeveeBitmasks
	dw VaporeonBitmasks
	dw JolteonBitmasks
	dw FlareonBitmasks
	dw PorygonBitmasks
	dw OmanyteBitmasks
	dw OmastarBitmasks
	dw KabutoBitmasks
	dw KabutopsBitmasks
	dw AerodactylBitmasks
	dw SnorlaxBitmasks
	dw ArticunoBitmasks
	dw ZapdosBitmasks
	dw MoltresBitmasks
	dw DratiniBitmasks
	dw DragonairBitmasks
	dw DragoniteBitmasks
	dw MewtwoBitmasks
	dw MewBitmasks
	dw ChikoritaBitmasks
	dw BayleefBitmasks
	dw MeganiumBitmasks
	dw CyndaquilBitmasks
	dw QuilavaBitmasks
	dw TyphlosionBitmasks
	dw TotodileBitmasks
	dw CroconawBitmasks
	dw FeraligatrBitmasks
	dw SentretBitmasks
	dw FurretBitmasks
	dw HoothootBitmasks
	dw NoctowlBitmasks
	dw LedybaBitmasks
	dw LedianBitmasks
	dw SpinarakBitmasks
	dw AriadosBitmasks
	dw CrobatBitmasks
	dw ChinchouBitmasks
	dw LanturnBitmasks
	dw PichuBitmasks
	dw CleffaBitmasks
	dw IgglybuffBitmasks
	dw TogepiBitmasks
	dw TogeticBitmasks
	dw NatuBitmasks
	dw XatuBitmasks
	dw MareepBitmasks
	dw FlaaffyBitmasks
	dw AmpharosBitmasks
	dw BellossomBitmasks
	dw MarillBitmasks
	dw AzumarillBitmasks
	dw SudowoodoBitmasks
	dw PolitoedBitmasks
	dw HoppipBitmasks
	dw SkiploomBitmasks
	dw JumpluffBitmasks
	dw AipomBitmasks
	dw SunkernBitmasks
	dw SunfloraBitmasks
	dw YanmaBitmasks
	dw WooperBitmasks
	dw QuagsireBitmasks
	dw EspeonBitmasks
	dw UmbreonBitmasks
	dw MurkrowBitmasks
	dw SlowkingBitmasks
	dw MisdreavusBitmasks
	dw UnownBitmasks
	dw WobbuffetBitmasks
	dw GirafarigBitmasks
	dw PinecoBitmasks
	dw ForretressBitmasks
	dw DunsparceBitmasks
	dw GligarBitmasks
	dw SteelixBitmasks
	dw SnubbullBitmasks
	dw GranbullBitmasks
	dw QwilfishBitmasks
	dw ScizorBitmasks
	dw ShuckleBitmasks
	dw HeracrossBitmasks
	dw SneaselBitmasks
	dw TeddiursaBitmasks
	dw UrsaringBitmasks
	dw SlugmaBitmasks
	dw MagcargoBitmasks
	dw SwinubBitmasks
	dw PiloswineBitmasks
	dw CorsolaBitmasks
	dw RemoraidBitmasks
	dw OctilleryBitmasks
	dw DelibirdBitmasks
	dw MantineBitmasks
	dw SkarmoryBitmasks
	dw HoundourBitmasks
	dw HoundoomBitmasks
	dw KingdraBitmasks
	dw PhanpyBitmasks
	dw DonphanBitmasks
	dw Porygon2Bitmasks
	dw StantlerBitmasks
	dw SmeargleBitmasks
	dw TyrogueBitmasks
	dw HitmontopBitmasks
	dw SmoochumBitmasks
	dw ElekidBitmasks
	dw MagbyBitmasks
	dw MiltankBitmasks
	dw BlisseyBitmasks
	dw RaikouBitmasks
	dw EnteiBitmasks
	dw SuicuneBitmasks
	dw LarvitarBitmasks
	dw PupitarBitmasks
	dw TyranitarBitmasks
	dw LugiaBitmasks
	dw HoOhBitmasks
	dw CelebiBitmasks
	dw TreeckoBitmasks
	dw GrovyleBitmasks
	dw SceptileBitmasks
	dw TorchicBitmasks
	dw CombuskenBitmasks
	dw BlazikenBitmasks
	dw MudkipBitmasks
	dw MarshtompBitmasks
	dw SwampertBitmasks
	dw PoochyenaBitmasks
	dw MightyenaBitmasks
	dw ZigzagoonBitmasks
	dw LinooneBitmasks
	dw LotadBitmasks
	dw LombreBitmasks
	dw LudicoloBitmasks
	dw TaillowBitmasks
	dw SwellowBitmasks
	dw WingullBitmasks
	dw PelipperBitmasks
	dw RaltsBitmasks
	dw KirliaBitmasks
	dw GardevoirBitmasks
	dw SurskitBitmasks
	dw MasquerainBitmasks
	dw WhismurBitmasks
	dw LoudredBitmasks
	dw ExploudBitmasks
	dw MakuhitaBitmasks
	dw HariyamaBitmasks
	dw AzurillBitmasks
	dw SkittyBitmasks
	dw DelcattyBitmasks
	dw SableyeBitmasks
	dw AronBitmasks
	dw LaironBitmasks
	dw AggronBitmasks
	dw ElectrikeBitmasks
	dw ManectricBitmasks
	dw RoseliaBitmasks
	dw WailmerBitmasks
	dw WailordBitmasks
	dw TrapinchBitmasks
	dw VibravaBitmasks
	dw FlygonBitmasks
	dw SwabluBitmasks
	dw AltariaBitmasks
	dw LileepBitmasks
	dw CradilyBitmasks
	dw FeebasBitmasks
	dw MiloticBitmasks
	dw DuskullBitmasks
	dw DusclopsBitmasks
	dw AbsolBitmasks
	dw SnoruntBitmasks
	dw SphealBitmasks
	dw SealeoBitmasks
	dw WalreinBitmasks
	dw BagonBitmasks
	dw ShelgonBitmasks
	dw SalamenceBitmasks
	dw BeldumBitmasks
	dw MetangBitmasks
	dw MetagrossBitmasks
	dw LatiosBitmasks
	dw KyogreBitmasks
	dw GroudonBitmasks
	dw TurtwigBitmasks
	dw GrotleBitmasks
	dw TorterraBitmasks
	dw ChimcharBitmasks
	dw PlaceholderBitmasks ; PLACEHOLDER - Monferno
	dw PlaceholderBitmasks ; PLACEHOLDER - Infernape
	dw PiplupBitmasks
	dw PrinplupBitmasks
	dw PlaceholderBitmasks ; PLACEHOLDER - Empoleon
	dw BidoofBitmasks
	dw BibarelBitmasks
	dw ShinxBitmasks
	dw LuxioBitmasks
	dw LuxrayBitmasks
	dw BudewBitmasks
	dw PlaceholderBitmasks ; PLACEHOLDER - Roserade
	dw BurmyBitmasks
	dw MothimBitmasks
	dw BuizelBitmasks
	dw PlaceholderBitmasks ; PLACEHOLDER - Floatzel
	dw ShellosBitmasks
	dw PlaceholderBitmasks ; PLACEHOLDER - Gastrodon
	dw BunearyBitmasks
	dw LopunnyBitmasks
	dw StunkyBitmasks
	dw SkuntankBitmasks
	dw BronzorBitmasks
	dw BronzongBitmasks
	dw BonslyBitmasks
	dw ChatotBitmasks
	dw CroagunkBitmasks
	dw ToxicroakBitmasks
	dw LeafeonBitmasks
	dw GlaceonBitmasks
	dw PorygonZBitmasks
	dw DusknoirBitmasks
	dw FroslassBitmasks
	dw DarkraiBitmasks
	dw PansageBitmasks
	dw SimisageBitmasks
	dw PlaceholderBitmasks ; PLACEHOLDER - Drilbur
	dw PlaceholderBitmasks ; PLACEHOLDER - Excadrill
	dw PlaceholderBitmasks ; PLACEHOLDER - Sandile
	dw PlaceholderBitmasks ; PLACEHOLDER - Krokorok
	dw KrookodileBitmasks
	dw DucklettBitmasks
	dw PlaceholderBitmasks ; PLACEHOLDER - Swanna
	dw TynamoBitmasks
	dw PlaceholderBitmasks ; PLACEHOLDER - Eelektrik
	dw PlaceholderBitmasks ; PLACEHOLDER - Eelektross
	dw LitwickBitmasks
	dw LampentBitmasks
	dw ChandelureBitmasks
	dw ClauncherBitmasks
	dw ClawitzerBitmasks
	dw PlaceholderBitmasks ; PLACEHOLDER - Helioptile
	dw HelioliskBitmasks
	dw PlaceholderBitmasks ; PLACEHOLDER - Amaura
	dw PlaceholderBitmasks ; PLACEHOLDER - Aurorus
	dw SylveonBitmasks
	dw GoomyBitmasks
	dw PlaceholderBitmasks ; PLACEHOLDER - Sliggoo
	dw GoodraBitmasks
	dw CrabrawlerBitmasks
	dw CrabominableBitmasks
	dw CutieflyBitmasks
	dw RibombeeBitmasks
	; Fused Crystal mons
	dw OnixtretBitmasks
	dw ChiquirtleBitmasks
	dw BaytortleBitmasks
	dw MegastoiseBitmasks
	dw HootduoBitmasks
	dw NoctdrioBitmasks
	dw TogekeyBitmasks
	dw TogetapeBitmasks
	dw HopporitaBitmasks
	dw SkipleefBitmasks
	dw JumpaniumBitmasks
	dw WoochumBitmasks
	dw QuagynxBitmasks
	dw SteelurretBitmasks
	; TPP's signature fakemon
	dw PhanceroBitmasks
