FramesPointers:
	dba BulbasaurFrames
	dba IvysaurFrames
	dba VenusaurFrames
	dba CharmanderFrames
	dba CharmeleonFrames
	dba CharizardFrames
	dba SquirtleFrames
	dba WartortleFrames
	dba BlastoiseFrames
	dba CaterpieFrames
	dba MetapodFrames
	dba ButterfreeFrames
	dba WeedleFrames
	dba KakunaFrames
	dba BeedrillFrames
	dba PidgeyFrames
	dba PidgeottoFrames
	dba PidgeotFrames
	dba RattataFrames
	dba RaticateFrames
	dba SpearowFrames
	dba FearowFrames
	dba EkansFrames
	dba ArbokFrames
	dba PikachuFrames
	dba RaichuFrames
	dba SandshrewFrames
	dba SandslashFrames
	dba NidoranFFrames
	dba NidorinaFrames
	dba NidoqueenFrames
	dba NidoranMFrames
	dba NidorinoFrames
	dba NidokingFrames
	dba ClefairyFrames
	dba ClefableFrames
	dba VulpixFrames
	dba NinetalesFrames
	dba JigglypuffFrames
	dba WigglytuffFrames
	dba ZubatFrames
	dba GolbatFrames
	dba OddishFrames
	dba GloomFrames
	dba VileplumeFrames
	dba ParasFrames
	dba ParasectFrames
	dba VenonatFrames
	dba VenomothFrames
	dba DiglettFrames
	dba DugtrioFrames
	dba MeowthFrames
	dba PersianFrames
	dba PsyduckFrames
	dba GolduckFrames
	dba MankeyFrames
	dba PrimeapeFrames
	dba GrowlitheFrames
	dba ArcanineFrames
	dba PoliwagFrames
	dba PoliwhirlFrames
	dba PoliwrathFrames
	dba AbraFrames
	dba KadabraFrames
	dba AlakazamFrames
	dba MachopFrames
	dba MachokeFrames
	dba MachampFrames
	dba BellsproutFrames
	dba WeepinbellFrames
	dba VictreebelFrames
	dba TentacoolFrames
	dba TentacruelFrames
	dba GeodudeFrames
	dba GravelerFrames
	dba GolemFrames
	dba PonytaFrames
	dba RapidashFrames
	dba SlowpokeFrames
	dba SlowbroFrames
	dba MagnemiteFrames
	dba MagnetonFrames
	dba FarfetchDFrames
	dba DoduoFrames
	dba DodrioFrames
	dba SeelFrames
	dba DewgongFrames
	dba GrimerFrames
	dba MukFrames
	dba ShellderFrames
	dba CloysterFrames
	dba GastlyFrames
	dba HaunterFrames
	dba GengarFrames
	dba OnixFrames
	dba DrowzeeFrames
	dba HypnoFrames
	dba KrabbyFrames
	dba KinglerFrames
	dba VoltorbFrames
	dba ElectrodeFrames
	dba ExeggcuteFrames
	dba ExeggutorFrames
	dba CuboneFrames
	dba MarowakFrames
	dba HitmonleeFrames
	dba HitmonchanFrames
	dba LickitungFrames
	dba KoffingFrames
	dba WeezingFrames
	dba RhyhornFrames
	dba RhydonFrames
	dba ChanseyFrames
	dba TangelaFrames
	dba KangaskhanFrames
	dba HorseaFrames
	dba SeadraFrames
	dba GoldeenFrames
	dba SeakingFrames
	dba StaryuFrames
	dba StarmieFrames
	dba MrMimeFrames
	dba ScytherFrames
	dba JynxFrames
	dba ElectabuzzFrames
	dba MagmarFrames
	dba PinsirFrames
	dba TaurosFrames
	dba MagikarpFrames
	dba GyaradosFrames
	dba LaprasFrames
	dba DittoFrames
	dba EeveeFrames
	dba VaporeonFrames
	dba JolteonFrames
	dba FlareonFrames
	dba PorygonFrames
	dba OmanyteFrames
	dba OmastarFrames
	dba KabutoFrames
	dba KabutopsFrames
	dba AerodactylFrames
	dba SnorlaxFrames
	dba ArticunoFrames
	dba ZapdosFrames
	dba MoltresFrames
	dba DratiniFrames
	dba DragonairFrames
	dba DragoniteFrames
	dba MewtwoFrames
	dba MewFrames
	dba ChikoritaFrames
	dba BayleefFrames
	dba MeganiumFrames
	dba CyndaquilFrames
	dba QuilavaFrames
	dba TyphlosionFrames
	dba TotodileFrames
	dba CroconawFrames
	dba FeraligatrFrames
	dba SentretFrames
	dba FurretFrames
	dba HoothootFrames
	dba NoctowlFrames
	dba LedybaFrames
	dba LedianFrames
	dba SpinarakFrames
	dba AriadosFrames
	dba CrobatFrames
	dba ChinchouFrames
	dba LanturnFrames
	dba PichuFrames
	dba CleffaFrames
	dba IgglybuffFrames
	dba TogepiFrames
	dba TogeticFrames
	dba NatuFrames
	dba XatuFrames
	dba MareepFrames
	dba FlaaffyFrames
	dba AmpharosFrames
	dba BellossomFrames
	dba MarillFrames
	dba AzumarillFrames
	dba SudowoodoFrames
	dba PolitoedFrames
	dba HoppipFrames
	dba SkiploomFrames
	dba JumpluffFrames
	dba AipomFrames
	dba SunkernFrames
	dba SunfloraFrames
	dba YanmaFrames
	dba WooperFrames
	dba QuagsireFrames
	dba EspeonFrames
	dba UmbreonFrames
	dba MurkrowFrames
	dba SlowkingFrames
	dba MisdreavusFrames
	dba UnownFrames
	dba WobbuffetFrames
	dba GirafarigFrames
	dba PinecoFrames
	dba ForretressFrames
	dba DunsparceFrames
	dba GligarFrames
	dba SteelixFrames
	dba SnubbullFrames
	dba GranbullFrames
	dba QwilfishFrames
	dba ScizorFrames
	dba ShuckleFrames
	dba HeracrossFrames
	dba SneaselFrames
	dba TeddiursaFrames
	dba UrsaringFrames
	dba SlugmaFrames
	dba MagcargoFrames
	dba SwinubFrames
	dba PiloswineFrames
	dba CorsolaFrames
	dba RemoraidFrames
	dba OctilleryFrames
	dba DelibirdFrames
	dba MantineFrames
	dba SkarmoryFrames
	dba HoundourFrames
	dba HoundoomFrames
	dba KingdraFrames
	dba PhanpyFrames
	dba DonphanFrames
	dba Porygon2Frames
	dba StantlerFrames
	dba SmeargleFrames
	dba TyrogueFrames
	dba HitmontopFrames
	dba SmoochumFrames
	dba ElekidFrames
	dba MagbyFrames
	dba MiltankFrames
	dba BlisseyFrames
	dba RaikouFrames
	dba EnteiFrames
	dba SuicuneFrames
	dba LarvitarFrames
	dba PupitarFrames
	dba TyranitarFrames
	dba LugiaFrames
	dba HoOhFrames
	dba CelebiFrames
	dba TreeckoFrames
	dba GrovyleFrames
	dba SceptileFrames
	dba TorchicFrames
	dba CombuskenFrames
	dba BlazikenFrames
	dba MudkipFrames
	dba MarshtompFrames
	dba SwampertFrames
	dba PoochyenaFrames
	dba MightyenaFrames
	dba ZigzagoonFrames
	dba LinooneFrames
	dba LotadFrames
	dba LombreFrames
	dba LudicoloFrames
	dba TaillowFrames
	dba SwellowFrames
	dba WingullFrames
	dba PelipperFrames
	dba RaltsFrames
	dba KirliaFrames
	dba GardevoirFrames
	dba SurskitFrames
	dba MasquerainFrames
	dba WhismurFrames
	dba LoudredFrames
	dba ExploudFrames
	dba MakuhitaFrames
	dba HariyamaFrames
	dba AzurillFrames
	dba SkittyFrames
	dba DelcattyFrames
	dba SableyeFrames
	dba AronFrames
	dba LaironFrames
	dba AggronFrames
	dba ElectrikeFrames
	dba ManectricFrames
	dba RoseliaFrames
	dba WailmerFrames
	dba WailordFrames
	dba TrapinchFrames
	dba VibravaFrames
	dba FlygonFrames
	dba SwabluFrames
	dba AltariaFrames
	dba LileepFrames
	dba CradilyFrames
	dba FeebasFrames
	dba MiloticFrames
	dba DuskullFrames
	dba DusclopsFrames
	dba AbsolFrames
	dba SnoruntFrames
	dba SphealFrames
	dba SealeoFrames
	dba WalreinFrames
	dba BagonFrames
	dba ShelgonFrames
	dba SalamenceFrames
	dba BeldumFrames
	dba MetangFrames
	dba MetagrossFrames
	dba LatiosFrames
	dba KyogreFrames
	dba GroudonFrames
	dba TurtwigFrames
	dba GrotleFrames
	dba TorterraFrames
	dba ChimcharFrames
	dba PlaceholderFrames ; PLACEHOLDER - Monferno
	dba PlaceholderFrames ; PLACEHOLDER - Infernape
	dba PiplupFrames
	dba PrinplupFrames
	dba PlaceholderFrames ; PLACEHOLDER - Empoleon
	dba BidoofFrames
	dba BibarelFrames
	dba ShinxFrames
	dba LuxioFrames
	dba LuxrayFrames
	dba BudewFrames
	dba PlaceholderFrames ; PLACEHOLDER - Roserade
	dba BurmyFrames
	dba MothimFrames
	dba BuizelFrames
	dba PlaceholderFrames ; PLACEHOLDER - Floatzel
	dba ShellosFrames
	dba PlaceholderFrames ; PLACEHOLDER - Gastrodon
	dba BunearyFrames
	dba LopunnyFrames
	dba PlaceholderFrames ; PLACEHOLDER - Stunky
	dba SkuntankFrames
	dba BronzorFrames
	dba BronzongFrames
	dba BonslyFrames
	dba ChatotFrames
	dba CroagunkFrames
	dba PlaceholderFrames ; PLACEHOLDER - Toxicroak
	dba LeafeonFrames
	dba GlaceonFrames
	dba PorygonZFrames
	dba DusknoirFrames
	dba FroslassFrames
	dba DarkraiFrames
	dba PlaceholderFrames ; PLACEHOLDER - Pansage
	dba SimisageFrames
	dba PlaceholderFrames ; PLACEHOLDER - Drilbur
	dba PlaceholderFrames ; PLACEHOLDER - Excadrill
	dba PlaceholderFrames ; PLACEHOLDER - Sandile
	dba PlaceholderFrames ; PLACEHOLDER - Krokorok
	dba KrookodileFrames
	dba PlaceholderFrames ; PLACEHOLDER - Ducklett
	dba PlaceholderFrames ; PLACEHOLDER - Swanna
	dba PlaceholderFrames ; PLACEHOLDER - Tynamo
	dba PlaceholderFrames ; PLACEHOLDER - Eelektrik
	dba PlaceholderFrames ; PLACEHOLDER - Eelektross
	dba LitwickFrames
	dba LampentFrames
	dba ChandelureFrames
	dba PlaceholderFrames ; PLACEHOLDER - Clauncher
	dba PlaceholderFrames ; PLACEHOLDER - Clawitzer
	dba PlaceholderFrames ; PLACEHOLDER - Helioptile
	dba PlaceholderFrames ; PLACEHOLDER - Heliolisk
	dba PlaceholderFrames ; PLACEHOLDER - Amaura
	dba PlaceholderFrames ; PLACEHOLDER - Aurorus
	dba SylveonFrames
	dba GoomyFrames
	dba PlaceholderFrames ; PLACEHOLDER - Sliggoo
	dba GoodraFrames
	dba CrabrawlerFrames
	dba CrabominableFrames
	dba PlaceholderFrames ; PLACEHOLDER - Cutiefly
	dba RibombeeFrames
	; Fused Crystal mons
	dba OnixtretFrames
	dba ChiquirtleFrames
	dba BaytortleFrames
	dba MegastoiseFrames
	dba HootduoFrames
	dba NoctdrioFrames
	dba TogekeyFrames
	dba TogetapeFrames
	dba HopporitaFrames
	dba SkipleefFrames
	dba JumpaniumFrames
	dba WoochumFrames
	dba QuagynxFrames
	dba SteelurretFrames
	; TPP's signature fakemon
	dba PhanceroFrames
