AnimationIdlePointers:
	dw BulbasaurAnimationIdle
	dw IvysaurAnimationIdle
	dw VenusaurAnimationIdle
	dw CharmanderAnimationIdle
	dw CharmeleonAnimationIdle
	dw CharizardAnimationIdle
	dw SquirtleAnimationIdle
	dw WartortleAnimationIdle
	dw BlastoiseAnimationIdle
	dw CaterpieAnimationIdle
	dw MetapodAnimationIdle
	dw ButterfreeAnimationIdle
	dw WeedleAnimationIdle
	dw KakunaAnimationIdle
	dw BeedrillAnimationIdle
	dw PidgeyAnimationIdle
	dw PidgeottoAnimationIdle
	dw PidgeotAnimationIdle
	dw RattataAnimationIdle
	dw RaticateAnimationIdle
	dw SpearowAnimationIdle
	dw FearowAnimationIdle
	dw EkansAnimationIdle
	dw ArbokAnimationIdle
	dw PikachuAnimationIdle
	dw RaichuAnimationIdle
	dw SandshrewAnimationIdle
	dw SandslashAnimationIdle
	dw NidoranFAnimationIdle
	dw NidorinaAnimationIdle
	dw NidoqueenAnimationIdle
	dw NidoranMAnimationIdle
	dw NidorinoAnimationIdle
	dw NidokingAnimationIdle
	dw ClefairyAnimationIdle
	dw ClefableAnimationIdle
	dw VulpixAnimationIdle
	dw NinetalesAnimationIdle
	dw JigglypuffAnimationIdle
	dw WigglytuffAnimationIdle
	dw ZubatAnimationIdle
	dw GolbatAnimationIdle
	dw OddishAnimationIdle
	dw GloomAnimationIdle
	dw VileplumeAnimationIdle
	dw ParasAnimationIdle
	dw ParasectAnimationIdle
	dw VenonatAnimationIdle
	dw VenomothAnimationIdle
	dw DiglettAnimationIdle
	dw DugtrioAnimationIdle
	dw MeowthAnimationIdle
	dw PersianAnimationIdle
	dw PsyduckAnimationIdle
	dw GolduckAnimationIdle
	dw MankeyAnimationIdle
	dw PrimeapeAnimationIdle
	dw GrowlitheAnimationIdle
	dw ArcanineAnimationIdle
	dw PoliwagAnimationIdle
	dw PoliwhirlAnimationIdle
	dw PoliwrathAnimationIdle
	dw AbraAnimationIdle
	dw KadabraAnimationIdle
	dw AlakazamAnimationIdle
	dw MachopAnimationIdle
	dw MachokeAnimationIdle
	dw MachampAnimationIdle
	dw BellsproutAnimationIdle
	dw WeepinbellAnimationIdle
	dw VictreebelAnimationIdle
	dw TentacoolAnimationIdle
	dw TentacruelAnimationIdle
	dw GeodudeAnimationIdle
	dw GravelerAnimationIdle
	dw GolemAnimationIdle
	dw PonytaAnimationIdle
	dw RapidashAnimationIdle
	dw SlowpokeAnimationIdle
	dw SlowbroAnimationIdle
	dw MagnemiteAnimationIdle
	dw MagnetonAnimationIdle
	dw FarfetchDAnimationIdle
	dw DoduoAnimationIdle
	dw DodrioAnimationIdle
	dw SeelAnimationIdle
	dw DewgongAnimationIdle
	dw GrimerAnimationIdle
	dw MukAnimationIdle
	dw ShellderAnimationIdle
	dw CloysterAnimationIdle
	dw GastlyAnimationIdle
	dw HaunterAnimationIdle
	dw GengarAnimationIdle
	dw OnixAnimationIdle
	dw DrowzeeAnimationIdle
	dw HypnoAnimationIdle
	dw KrabbyAnimationIdle
	dw KinglerAnimationIdle
	dw VoltorbAnimationIdle
	dw ElectrodeAnimationIdle
	dw ExeggcuteAnimationIdle
	dw ExeggutorAnimationIdle
	dw CuboneAnimationIdle
	dw MarowakAnimationIdle
	dw HitmonleeAnimationIdle
	dw HitmonchanAnimationIdle
	dw LickitungAnimationIdle
	dw KoffingAnimationIdle
	dw WeezingAnimationIdle
	dw RhyhornAnimationIdle
	dw RhydonAnimationIdle
	dw ChanseyAnimationIdle
	dw TangelaAnimationIdle
	dw KangaskhanAnimationIdle
	dw HorseaAnimationIdle
	dw SeadraAnimationIdle
	dw GoldeenAnimationIdle
	dw SeakingAnimationIdle
	dw StaryuAnimationIdle
	dw StarmieAnimationIdle
	dw MrMimeAnimationIdle
	dw ScytherAnimationIdle
	dw JynxAnimationIdle
	dw ElectabuzzAnimationIdle
	dw MagmarAnimationIdle
	dw PinsirAnimationIdle
	dw TaurosAnimationIdle
	dw MagikarpAnimationIdle
	dw GyaradosAnimationIdle
	dw LaprasAnimationIdle
	dw DittoAnimationIdle
	dw EeveeAnimationIdle
	dw VaporeonAnimationIdle
	dw JolteonAnimationIdle
	dw FlareonAnimationIdle
	dw PorygonAnimationIdle
	dw OmanyteAnimationIdle
	dw OmastarAnimationIdle
	dw KabutoAnimationIdle
	dw KabutopsAnimationIdle
	dw AerodactylAnimationIdle
	dw SnorlaxAnimationIdle
	dw ArticunoAnimationIdle
	dw ZapdosAnimationIdle
	dw MoltresAnimationIdle
	dw DratiniAnimationIdle
	dw DragonairAnimationIdle
	dw DragoniteAnimationIdle
	dw MewtwoAnimationIdle
	dw MewAnimationIdle
	dw ChikoritaAnimationIdle
	dw BayleefAnimationIdle
	dw MeganiumAnimationIdle
	dw CyndaquilAnimationIdle
	dw QuilavaAnimationIdle
	dw TyphlosionAnimationIdle
	dw TotodileAnimationIdle
	dw CroconawAnimationIdle
	dw FeraligatrAnimationIdle
	dw SentretAnimationIdle
	dw FurretAnimationIdle
	dw HoothootAnimationIdle
	dw NoctowlAnimationIdle
	dw LedybaAnimationIdle
	dw LedianAnimationIdle
	dw SpinarakAnimationIdle
	dw AriadosAnimationIdle
	dw CrobatAnimationIdle
	dw ChinchouAnimationIdle
	dw LanturnAnimationIdle
	dw PichuAnimationIdle
	dw CleffaAnimationIdle
	dw IgglybuffAnimationIdle
	dw TogepiAnimationIdle
	dw TogeticAnimationIdle
	dw NatuAnimationIdle
	dw XatuAnimationIdle
	dw MareepAnimationIdle
	dw FlaaffyAnimationIdle
	dw AmpharosAnimationIdle
	dw BellossomAnimationIdle
	dw MarillAnimationIdle
	dw AzumarillAnimationIdle
	dw SudowoodoAnimationIdle
	dw PolitoedAnimationIdle
	dw HoppipAnimationIdle
	dw SkiploomAnimationIdle
	dw JumpluffAnimationIdle
	dw AipomAnimationIdle
	dw SunkernAnimationIdle
	dw SunfloraAnimationIdle
	dw YanmaAnimationIdle
	dw WooperAnimationIdle
	dw QuagsireAnimationIdle
	dw EspeonAnimationIdle
	dw UmbreonAnimationIdle
	dw MurkrowAnimationIdle
	dw SlowkingAnimationIdle
	dw MisdreavusAnimationIdle
	dw UnownAnimationIdle
	dw WobbuffetAnimationIdle
	dw GirafarigAnimationIdle
	dw PinecoAnimationIdle
	dw ForretressAnimationIdle
	dw DunsparceAnimationIdle
	dw GligarAnimationIdle
	dw SteelixAnimationIdle
	dw SnubbullAnimationIdle
	dw GranbullAnimationIdle
	dw QwilfishAnimationIdle
	dw ScizorAnimationIdle
	dw ShuckleAnimationIdle
	dw HeracrossAnimationIdle
	dw SneaselAnimationIdle
	dw TeddiursaAnimationIdle
	dw UrsaringAnimationIdle
	dw SlugmaAnimationIdle
	dw MagcargoAnimationIdle
	dw SwinubAnimationIdle
	dw PiloswineAnimationIdle
	dw CorsolaAnimationIdle
	dw RemoraidAnimationIdle
	dw OctilleryAnimationIdle
	dw DelibirdAnimationIdle
	dw MantineAnimationIdle
	dw SkarmoryAnimationIdle
	dw HoundourAnimationIdle
	dw HoundoomAnimationIdle
	dw KingdraAnimationIdle
	dw PhanpyAnimationIdle
	dw DonphanAnimationIdle
	dw Porygon2AnimationIdle
	dw StantlerAnimationIdle
	dw SmeargleAnimationIdle
	dw TyrogueAnimationIdle
	dw HitmontopAnimationIdle
	dw SmoochumAnimationIdle
	dw ElekidAnimationIdle
	dw MagbyAnimationIdle
	dw MiltankAnimationIdle
	dw BlisseyAnimationIdle
	dw RaikouAnimationIdle
	dw EnteiAnimationIdle
	dw SuicuneAnimationIdle
	dw LarvitarAnimationIdle
	dw PupitarAnimationIdle
	dw TyranitarAnimationIdle
	dw LugiaAnimationIdle
	dw HoOhAnimationIdle
	dw CelebiAnimationIdle
	dw TreeckoAnimationIdle
	dw GrovyleAnimationIdle
	dw SceptileAnimationIdle
	dw TorchicAnimationIdle
	dw CombuskenAnimationIdle
	dw BlazikenAnimationIdle
	dw MudkipAnimationIdle
	dw MarshtompAnimationIdle
	dw SwampertAnimationIdle
	dw PoochyenaAnimationIdle
	dw MightyenaAnimationIdle
	dw ZigzagoonAnimationIdle
	dw LinooneAnimationIdle
	dw LotadAnimationIdle
	dw LombreAnimationIdle
	dw LudicoloAnimationIdle
	dw TaillowAnimationIdle
	dw SwellowAnimationIdle
	dw WingullAnimationIdle
	dw PelipperAnimationIdle
	dw RaltsAnimationIdle
	dw KirliaAnimationIdle
	dw GardevoirAnimationIdle
	dw SurskitAnimationIdle
	dw MasquerainAnimationIdle
	dw WhismurAnimationIdle
	dw LoudredAnimationIdle
	dw ExploudAnimationIdle
	dw MakuhitaAnimationIdle
	dw HariyamaAnimationIdle
	dw AzurillAnimationIdle
	dw SkittyAnimationIdle
	dw DelcattyAnimationIdle
	dw SableyeAnimationIdle
	dw AronAnimationIdle
	dw LaironAnimationIdle
	dw AggronAnimationIdle
	dw ElectrikeAnimationIdle
	dw ManectricAnimationIdle
	dw RoseliaAnimationIdle
	dw WailmerAnimationIdle
	dw WailordAnimationIdle
	dw TrapinchAnimationIdle
	dw VibravaAnimationIdle
	dw FlygonAnimationIdle
	dw SwabluAnimationIdle
	dw AltariaAnimationIdle
	dw LileepAnimationIdle
	dw CradilyAnimationIdle
	dw FeebasAnimationIdle
	dw MiloticAnimationIdle
	dw DuskullAnimationIdle
	dw DusclopsAnimationIdle
	dw AbsolAnimationIdle
	dw SnoruntAnimationIdle
	dw SphealAnimationIdle
	dw SealeoAnimationIdle
	dw WalreinAnimationIdle
	dw BagonAnimationIdle
	dw ShelgonAnimationIdle
	dw SalamenceAnimationIdle
	dw BeldumAnimationIdle
	dw MetangAnimationIdle
	dw MetagrossAnimationIdle
	dw LatiosAnimationIdle
	dw KyogreAnimationIdle
	dw GroudonAnimationIdle
	dw TurtwigAnimationIdle
	dw GrotleAnimationIdle
	dw TorterraAnimationIdle
	dw ChimcharAnimationIdle
	dw PlaceholderAnimationIdle ; PLACEHOLDER - Monferno
	dw PlaceholderAnimationIdle ; PLACEHOLDER - Infernape
	dw PiplupAnimationIdle
	dw PrinplupAnimationIdle
	dw PlaceholderAnimationIdle ; PLACEHOLDER - Empoleon
	dw BidoofAnimationIdle
	dw BibarelAnimationIdle
	dw ShinxAnimationIdle
	dw LuxioAnimationIdle
	dw LuxrayAnimationIdle
	dw BudewAnimationIdle
	dw PlaceholderAnimationIdle ; PLACEHOLDER - Roserade
	dw BurmyAnimationIdle
	dw MothimAnimationIdle
	dw BuizelAnimationIdle
	dw PlaceholderAnimationIdle ; PLACEHOLDER - Floatzel
	dw ShellosAnimationIdle
	dw PlaceholderAnimationIdle ; PLACEHOLDER - Gastrodon
	dw BunearyAnimationIdle
	dw LopunnyAnimationIdle
	dw PlaceholderAnimationIdle ; PLACEHOLDER - Stunky
	dw SkuntankAnimationIdle
	dw BronzorAnimationIdle
	dw BronzongAnimationIdle
	dw BonslyAnimationIdle
	dw ChatotAnimationIdle
	dw CroagunkAnimationIdle
	dw ToxicroakAnimationIdle
	dw LeafeonAnimationIdle
	dw GlaceonAnimationIdle
	dw PorygonZAnimationIdle
	dw DusknoirAnimationIdle
	dw FroslassAnimationIdle
	dw DarkraiAnimationIdle
	dw PlaceholderAnimationIdle ; PLACEHOLDER - Pansage
	dw SimisageAnimationIdle
	dw PlaceholderAnimationIdle ; PLACEHOLDER - Drilbur
	dw PlaceholderAnimationIdle ; PLACEHOLDER - Excadrill
	dw PlaceholderAnimationIdle ; PLACEHOLDER - Sandile
	dw PlaceholderAnimationIdle ; PLACEHOLDER - Krokorok
	dw KrookodileAnimationIdle
	dw DucklettAnimationIdle
	dw PlaceholderAnimationIdle ; PLACEHOLDER - Swanna
	dw TynamoAnimationIdle
	dw PlaceholderAnimationIdle ; PLACEHOLDER - Eelektrik
	dw PlaceholderAnimationIdle ; PLACEHOLDER - Eelektross
	dw LitwickAnimationIdle
	dw LampentAnimationIdle
	dw ChandelureAnimationIdle
	dw ClauncherAnimationIdle
	dw ClawitzerAnimationIdle
	dw PlaceholderAnimationIdle ; PLACEHOLDER - Helioptile
	dw HelioliskAnimationIdle
	dw PlaceholderAnimationIdle ; PLACEHOLDER - Amaura
	dw PlaceholderAnimationIdle ; PLACEHOLDER - Aurorus
	dw SylveonAnimationIdle
	dw GoomyAnimationIdle
	dw PlaceholderAnimationIdle ; PLACEHOLDER - Sliggoo
	dw GoodraAnimationIdle
	dw CrabrawlerAnimationIdle
	dw CrabominableAnimationIdle
	dw CutieflyAnimationIdle
	dw RibombeeAnimationIdle
	; Fused Crystal mons
	dw OnixtretAnimationIdle
	dw ChiquirtleAnimationIdle
	dw BaytortleAnimationIdle
	dw MegastoiseAnimationIdle
	dw HootduoAnimationIdle
	dw NoctdrioAnimationIdle
	dw TogekeyAnimationIdle
	dw TogetapeAnimationIdle
	dw HopporitaAnimationIdle
	dw SkipleefAnimationIdle
	dw JumpaniumAnimationIdle
	dw WoochumAnimationIdle
	dw QuagynxAnimationIdle
	dw SteelurretAnimationIdle
	; TPP's signature fakemon
	dw PhanceroAnimationIdle
